repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ["--target-version", "py38"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.290'
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        types: [python]
        args: []  # TODO: enable this: "--check-untyped-defs"
        exclude: ^tests  # TODO: narrow it down to: ^tests/testdata/typing
        additional_dependencies: [
          pydantic==1.*,
          types-python-dateutil,
          types-requests,
          types-urllib3,
          types-redis,
          types-cachetools,
          types-tabulate
        ]
