repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # - id: trailing-whitespace # TODO: enable this
      # - id: end-of-file-fixer  # TODO: enable this
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ["--target-version", "py38"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.290'
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        types: [python]
        args: []  # TODO: enable this: "--check-untyped-defs"
        # TODO: narrow tests exclusion down to: ^tests/testdata/typing/*$
        exclude: |
          (?x)^(
              .vulture.py|
              tests/.*
          )$
        additional_dependencies: [
          pydantic==1.*,
          types-python-dateutil,
          types-requests,
          types-urllib3,
          types-redis,
          types-cachetools,
          types-tabulate
        ]

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.9.1
    hooks:
      - id: vulture
        args: ["--min-confidence", "90", "modelkit", "bin", ".vulture.py"]
