name: docs

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    if: ${{github.ref == 'refs/heads/main'}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: Install dependencies
        run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin

      - name: Build and deploy docs
        run: mkdocs gh-deploy --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Download Coverage Report
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          name: coverage
          path: coverage

      - name: Push Coverage Report
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add coverage
          git commit -m "add coverage report"
          git push
