name: docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: gh-pages
          soft_fail: true

      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: Install dependencies
        run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin

      - name: Build and deploy docs
        run: mkdocs gh-deploy --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}